<a href="https://colab.research.google.com/github/chanchleshmalvi01/NumPy-Assignment-/blob/main/numpyassignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


import numpy as np

arr = np.arange(6)
print("Array:", arr)
print("Data type" ,arr.dtype)

Array: [0 1 2 3 4 5]
Data type int64


In [ ]:
# 2. Given a NumPy array 'arr', check if its data type is float64.
# arr = np.array([1.5, 2.6, 3.7])

import numpy as np


arr = np.array([1.5, 2.6, 3.7])

is_float64 = arr.dtype == np.float64

print("Is the data type float64?", is_float64)


Is the data type float64? True


In [ ]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

#code

import numpy as np

arr = np.array([0.5+0.25j, 1.0+1.0j, 1.5+0.75j], dtype=np.complex128)

print("Array:", arr)
print("Data type:", arr.dtype)


Array: [0.5+0.25j 1. +1.j   1.5+0.75j]
Data type: complex128


In [ ]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type

# code

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr_float32 = arr.astype(np.float32)

print(arr_float32)

[1. 2. 3. 4. 5.]


In [17]:
#  5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

import numpy as np

arr = np.array([1.123456789, 2.987654321, 3.141592653], dtype='float64')

print("Original array data type:", arr.dtype)

arr_float32 = arr.astype(np.float32)

print("Converted array data type:", arr_float32.dtype)



Original array data type: float64
Converted array data type: float32


In [ ]:
 #6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
#code

import numpy as np

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype


arr = np.array([1.5, 2.6, 3.7])
attributes = array_attributes(arr)
print("Shape:", attributes[0])
print("Size:", attributes[1])
print("Data type:", attributes[2])


Shape: (3,)
Size: 3
Data type: float64


In [ ]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

import numpy as np

def array_dimension(arr):

    return arr.ndim


arr = np.array([[3,4,5], [6,7,8]])
dimensionality = array_dimension(arr)
print("Dimensionality:", dimensionality)


Dimensionality: 2


In [19]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

# Code
import numpy as np

def item_size_info(arr):
    if isinstance(arr, np.ndarray):
        item_size = arr.itemsize
        total_size = arr.nbytes
        print(f"Item size: {item_size} bytes")
        print(f"Total size: {total_size} bytes")
    else:
        print("Invalid input. Please provide a NumPy array.")
        arr = np.array([1.123456789, 2.987654321, 3.141592653, 4.567890123, 5.678901234])
item_size_info(arr)




Item size: 8 bytes
Total size: 40 bytes


In [20]:
 #9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

# Code

import numpy as np

def array_strides(input_array):
    if isinstance(input_array, np.ndarray):
        return input_array.strides
    else:
        raise ValueError("Input is not a NumPy array")

# New input array
my_array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(array_strides(my_array))



(24, 8)


In [ ]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.


# Code

import numpy as np

def array_strides(input_array):
    if isinstance(input_array, np.ndarray):
        return input_array.strides
    else:
        raise ValueError("Input is not a NumPy array")

my_array = np.array([[4,3,5], [4,5,3]])
print("My array:")
print(my_array)
print("\nStrides of my array:")
print(array_strides(my_array))

My array:
[[4 3 5]
 [4 5 3]]

Strides of my array:
(24, 8)


In [21]:
#  11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.



# Code

import numpy as np

def create_zeros_array(n):

    return np.zeros(n)

print(create_zeros_array(int(input())))


7
[0. 0. 0. 0. 0. 0. 0.]


In [22]:
#  12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`

# Code
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

rows = 3
cols = 5
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
#  13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step`.


# code

import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

start = 0
stop = 20
step = 3
range_array = generate_range_array(start, stop, step)
print(range_array)

[ 0  3  6  9 12 15 18]


In [24]:
#  14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as  arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).


# code

import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage:
start = 1.0
stop = 2.0
num = 5
linear_space = generate_linear_space(start, stop, num)
print(linear_space)


[1.   1.25 1.5  1.75 2.  ]


In [25]:
#  15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.


# code

import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
#  16. Write a function that takes a Python list and converts it into a NumPy array.


# code

import numpy as np

def list_to_numpy_array(lst):
    return np.array(lst)

lst = [3 , 5, 7]
numpy_array = list_to_numpy_array(lst)
print(numpy_array)

[3 5 7]


In [26]:
#  17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

# code

import numpy as np

arr = np.array([3,4,5,6,7])

new_arr = arr.view()

print("Original array:")
print(arr)
print("\nNew array:")
print(new_arr)

new_arr[0] = 10
print("\nOriginal array after modifying new array:")
print(arr)

Original array:
[3 4 5 6 7]

New array:
[3 4 5 6 7]

Original array after modifying new array:
[10  4  5  6  7]


In [103]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

#code

import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    try:
        concatenated_array = np.concatenate((arr1, arr2), axis=axis)
        return concatenated_array
    except ValueError as e:
        return f"Error: {e}"

# Example usage:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

# Concatenating along axis 0
result_axis0 = concatenate_arrays(arr1, arr2, axis=0)
print("\nConcatenated along axis 0:")
print(result_axis0)

# Concatenating along axis 1
result_axis1 = concatenate_arrays(arr1, arr2, axis=1)
print("\nConcatenated along axis 1:")
print(result_axis1)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [28]:
# 19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.



# Code

import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10]])

array2_extended = np.concatenate((array2, np.zeros((array2.shape[0], 1))), axis=1)

result = np.concatenate((array1, array2_extended), axis=1)

print(result)

[[ 1.  2.  3.  7.  8.  0.]
 [ 4.  5.  6.  9. 10.  0.]]


In [29]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

# Code
import numpy as np

def stack_arrays_vertically(arrays_list):

    stacked_array = np.vstack(arrays_list)
    return stacked_array

array1 = np.array([10, 20, 30])
array2 = np.array([40, 50, 60])
array3 = np.array([70, 80, 90])

stacked_array = stack_arrays_vertically([array1, array2, array3])
print(stacked_array)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [30]:
#  21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)  with a given step size.

# code

import numpy as np

def create_integer_array(start, end, step=1):

    if step == 0:
        raise ValueError("Step size cannot be zero.")

    integer_array = np.arange(start, end + 1, step)
    return integer_array
integer_array = create_integer_array(5, 25, 5)
print(integer_array)

[ 5 10 15 20 25]


In [31]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

# code

import numpy as np

def generate_equally_spaced_values(start, end, num_values):

    if num_values <= 0:
        raise ValueError("Number of values must be greater than zero.")

    equally_spaced_values = np.linspace(start, end, num_values)
    return equally_spaced_values

equally_spaced_values = generate_equally_spaced_values(5, 15, 6)
print(equally_spaced_values)

[ 5.  7.  9. 11. 13. 15.]


In [33]:
#  23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


# code
import numpy as np

def generate_log_array():
    return np.logspace(2, 4, 7, endpoint=True)

print(generate_log_array())


[  100.           215.443469     464.15888336  1000.
  2154.43469003  4641.58883361 10000.        ]


In [34]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

# code
import numpy as np
import pandas as pd

np_array = np.random.randint(50, 151, size=(6, 4))

print("NumPy Array:")
print(np_array)

df = pd.DataFrame(np_array, columns=['Column_1', 'Column_2', 'Column_3', 'Column_4'])

print("\nPandas DataFrame:")
print(df)

NumPy Array:
[[115  67 136 120]
 [125 100  85 131]
 [ 76 111 135 118]
 [ 94  70 150  56]
 [ 85  97  88 145]
 [ 51  61 100 118]]

Pandas DataFrame:
   Column_1  Column_2  Column_3  Column_4
0       115        67       136       120
1       125       100        85       131
2        76       111       135       118
3        94        70       150        56
4        85        97        88       145
5        51        61       100       118


In [36]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific columnwith zeros. Use NumPy operations within the Pandas DataFrame.

# code

import numpy as np
import pandas as pd

# New DataFrame with different values
df = pd.DataFrame({'A': [10, -20, 30, -40, 50], 'B': [-60, 70, -80, 90, -100]})

print("Original DataFrame:")
print(df)

def replace_negatives_with_zeros(df, column_name):
    df.loc[:, column_name] = np.where(df[column_name] < 0, 0, df[column_name])

replace_negatives_with_zeros(df, 'A')

print("\nDataFrame after replacing the negative values in column 'A' with zeros:")
print(df)

replace_negatives_with_zeros(df, 'B')

print("\nDataFrame after replacing the negative values in column 'B' with zeros:")
print(df)


Original DataFrame:
    A    B
0  10  -60
1 -20   70
2  30  -80
3 -40   90
4  50 -100

DataFrame after replacing the negative values in column 'A' with zeros:
    A    B
0  10  -60
1   0   70
2  30  -80
3   0   90
4  50 -100

DataFrame after replacing the negative values in column 'B' with zeros:
    A   B
0  10   0
1   0  70
2  30   0
3   0  90
4  50   0


In [40]:
# 26. Access the 3rd element from the given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])


# code
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

third_element = arr[2]

print("The 3rd element from the array is:", third_element)


The 3rd element from the array is: 30


In [41]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

# arr_2d = np.array([[1, 2, 3],
                   # [4, 5, 6],
                   # [7, 8, 9]])

# code
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]

print("The element at index (1, 2) from the array is:", element)

The element at index (1, 2) from the array is: 6


In [42]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
# arr = np.array([3, 8, 2, 10, 5, 7])

# code
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])
greater_than_5 = arr[arr > 5]

print("The elements greater than 5 from the array are:", greater_than_5)

The elements greater than 5 from the array are: [ 8 10  7]


In [43]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# code
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_arr = arr[2:6]
print("The elements from index 2 to 5 (inclusive) from the array are:", sliced_arr)

The elements from index 2 to 5 (inclusive) from the array are: [3 4 5 6]


In [44]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
# arr_2d = np.array([[1, 2, 3],
                   # [4, 5, 6],
                   # [7, 8, 9]])

# code

import numpy as np

import numpy as np
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

sub_arr = arr_2d[1:, :2]
print("The extracted sub-array is:\n", sub_arr)


The extracted sub-array is:
 [[4 5]
 [7 8]]


In [45]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

# code
import numpy as np

def extract_elements(arr_2d, indices):
    extracted_elements = arr_2d[tuple(indices.T.tolist())]
    return extracted_elements

arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

indices = np.array([[0, 0],
                      [1, 2],
                      [2, 1]])

extracted_elements = extract_elements(arr_2d, indices)

print("The extracted elements in the specified order are:", extracted_elements)

The extracted elements in the specified order are: [1 6 8]


In [46]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

# code
import numpy as np

def filter_greater_than(arr, threshold):

    filtered_arr = arr[arr > threshold]

    return filtered_arr
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

filtered_arr = filter_greater_than(arr, 5)

print("The elements greater than 5 are:", filtered_arr)

The elements greater than 5 are: [6 7 8 9]


In [47]:
  # 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

# code
import numpy as np

def extract_elements_3d(array, x_indices, y_indices, z_indices):
    return array[x_indices, y_indices, z_indices]

array_3d = np.random.randint(1, 100, size=(4, 4, 4))
print("Original 3D array:")
print(array_3d)

x_indices = np.array([0, 2, 3])
y_indices = np.array([1, 1, 3])
z_indices = np.array([1, 2, 3])

extracted_elements = extract_elements_3d(array_3d, x_indices, y_indices, z_indices)
print("\nExtracted elements:")
print(extracted_elements)


Original 3D array:
[[[72 62 90  9]
  [96  4 64 24]
  [66 84 47 56]
  [52  4 37 83]]

 [[12 87 36 64]
  [81  6 71 55]
  [13 75 53 96]
  [93 71 76 51]]

 [[41 14 66 61]
  [57 83 28 98]
  [83 49 89  6]
  [ 3 31 70 48]]

 [[95 14  3 80]
  [61 56 69 82]
  [51 73 87 79]
  [36 68 53  9]]]

Extracted elements:
[ 4 28  9]


In [48]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

# code


import numpy as np

def filter_two_conditions(arr, condition1, condition2):
    filtered_arr = arr[(condition1) & (condition2)]
    return filtered_arr

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition1 = (arr > 3)
condition2 = (arr % 2 == 0)
filtered_arr = filter_two_conditions(arr, condition1, condition2)
print("The elements greater than 3 and even are:", filtered_arr)

The elements greater than 3 and even are: [4 6 8]


In [49]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

# code
import numpy as np

def extract_elements_2d(arr, row_indices, col_indices):
    extracted_elements = arr[row_indices, col_indices]
    return extracted_elements

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 1])
extracted_elements = extract_elements_2d(arr, row_indices, col_indices)
print("The extracted elements are:", extracted_elements)


The extracted elements are: [30 40 80]


In [50]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

# code


import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
result = arr + 5

print("The array after adding 5 to each element is:")
print(result)

The array after adding 5 to each element is:
[[15 25 35]
 [45 55 65]
 [75 85 95]]


In [51]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

# code


import numpy as np

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)

result = arr2 * arr1.T

print("\nResult of broadcasting multiplication:")
print(result)

Array arr1:
[[2 3 4]]

Array arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result of broadcasting multiplication:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [52]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

# code


import numpy as np

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)

result = arr2 * arr1.T

print("\nResult of broadcasting multiplication:")
print(result)

Array arr1:
[[2 3 4]]

Array arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result of broadcasting multiplication:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [53]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

# code


import numpy as np

arr1 = np.array([[1],
                [2],
                [3]])
arr2 = np.array([[4, 5, 6]])

result = arr1 + arr2

print("The resulting array after adding arr1 and arr2 is:")
print(result)

The resulting array after adding arr1 and arr2 is:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [54]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

# code

import numpy as np

arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr2 = np.array([
    [10, 11],
    [12, 13],
    [14, 15]
])

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)

arr2_broadcast = np.broadcast_to(arr2[:, np.newaxis, :], (3, 3, 2))


result = arr1[:, :, np.newaxis] * arr2_broadcast

print("\nResult of broadcasting multiplication:")
print(result)


Array arr1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array arr2:
[[10 11]
 [12 13]
 [14 15]]

Result of broadcasting multiplication:
[[[ 10  11]
  [ 20  22]
  [ 30  33]]

 [[ 48  52]
  [ 60  65]
  [ 72  78]]

 [[ 98 105]
  [112 120]
  [126 135]]]


In [55]:
# 41. Calculate column wise mean for the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# code


import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column wise mean
col_mean = np.mean(arr, axis=0)

print("The column wise mean of the array is:")
print(col_mean)

The column wise mean of the array is:
[2.5 3.5 4.5]


In [56]:
# 42. Find maximum value in each row of the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# code

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find maximum value in each row
row_max = np.max(arr, axis=1)

print("The maximum value in each row of the array is:")
print(row_max)

The maximum value in each row of the array is:
[3 6]


In [57]:
# 43. For the given array, find indices of maximum value in each column.
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# code


import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find indices of maximum value in each column
col_max_indices = np.argmax(arr, axis=0)

print("The indices of the maximum value in each column of the array are:")
print(col_max_indices)

The indices of the maximum value in each column of the array are:
[1 1 1]


In [58]:
# 44. For the given array, apply custom function to calculate moving sum along rows.
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# code

import numpy as np

def moving_sum(arr, window_size=2):
    result = np.zeros((arr.shape[0], arr.shape[1] - window_size + 1))
    for i in range(arr.shape[1] - window_size + 1):
        result[:, i] = np.sum(arr[:, i:i+window_size], axis=1)
    return result

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(arr)

result = moving_sum(arr, window_size=2)
print("\nMoving sum along rows with window size 2:")
print(result)

Original array:
[[1 2 3]
 [4 5 6]]

Moving sum along rows with window size 2:
[[ 3.  5.]
 [ 9. 11.]]


In [59]:
# 45. In the given array, check if all elements in each column are even.
# arr = np.array([[2, 4, 6], [3, 5, 7]])
# code


import numpy as np

arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if all elements in each column are even
is_even = np.all(arr % 2 == 0, axis=0)

print("The result of checking if all elements in each column are even is:")
print(is_even)

The result of checking if all elements in each column are even is:
[False False False]


In [60]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the reshaped matrix.
# original_array = np.array([1, 2, 3, 4, 5, 6])

# code


import numpy as np

def reshape_matrix(arr, m, n):

    reshaped_matrix = np.reshape(arr, (m, n))

    return reshaped_matrix

original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_matrix = reshape_matrix(original_array, 2, 3)

print("The reshaped matrix is:")
print(reshaped_matrix)

The reshaped matrix is:
[[1 2 3]
 [4 5 6]]


In [61]:
# 47. Create a function that takes a matrix as input and returns the flattened array.
# input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
# code


import numpy as np

def flatten_matrix(matrix):

    flattened_array = np.ravel(matrix)

    return flattened_array

input_matrix = np.array([[1, 2, 3],
                          [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)

print("The flattened array is:")
print(flattened_array)

The flattened array is:
[1 2 3 4 5 6]


In [62]:
# 48. Write a function that concatenates two given arrays along a specified axis.
# array1 = np.array([[1, 2], [3, 4]])
# array2 = np.array([[5, 6], [7, 8]])
# code


import numpy as np

def concatenate_arrays(array1, array2, axis=0):

    output_array = np.concatenate((array1, array2), axis=axis)

    return output_array

array1 = np.array([[1, 2],
                      [3, 4]])

array2 = np.array([[5, 6],
                      [7, 8]])
output_array = concatenate_arrays(array1, array2)

print("The output array after concatenation along the default axis (axis=0) is:")
print(output_array)

output_array = concatenate_arrays(array1, array2, axis=1)

print("The output array after concatenation along the other axis (axis=1) is:")
print(output_array)

The output array after concatenation along the default axis (axis=0) is:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
The output array after concatenation along the other axis (axis=1) is:
[[1 2 5 6]
 [3 4 7 8]]


In [63]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
# original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# code

import numpy as np

def split_array(arr, num_splits, axis=0):

    return np.array_split(arr, num_splits, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:")
print(original_array)

sub_arrays_axis_0 = split_array(original_array, 3, axis=0)
print("\nSplit array along axis 0:")
for i, sub_array in enumerate(sub_arrays_axis_0):
    print(f"Sub-array {i}:\n{sub_array}")

sub_arrays_axis_1 = split_array(original_array, 3, axis=1)
print("\nSplit array along axis 1:")
for i, sub_array in enumerate(sub_arrays_axis_1):
    print(f"Sub-array {i}:\n{sub_array}")

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Split array along axis 0:
Sub-array 0:
[[1 2 3]]
Sub-array 1:
[[4 5 6]]
Sub-array 2:
[[7 8 9]]

Split array along axis 1:
Sub-array 0:
[[1]
 [4]
 [7]]
Sub-array 1:
[[2]
 [5]
 [8]]
Sub-array 2:
[[3]
 [6]
 [9]]


In [64]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
# original_array = np.array([1, 2, 3, 4, 5])
# indices_to_insert = [2, 4]
# values_to_insert = [10, 11]
# indices_to_delete = [1, 3]

# code

import numpy as np

def insert_and_delete_elements(arr, indices_to_insert, values_to_insert, indices_to_delete):

    modified_array = np.insert(arr, indices_to_insert, values_to_insert)

    modified_array = np.delete(modified_array, indices_to_delete)

    return modified_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

print("Original array:")
print(original_array)

result = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("\nModified array after insertion and deletion:")
print(result)

Original array:
[1 2 3 4 5]

Modified array after insertion and deletion:
[ 1 10  4 11  5]


In [65]:
# 51. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2.

# code

import numpy as np

arr1 = np.random.randint(1, 100, size=10)
print("Array arr1:")
print(arr1)

arr2 = np.arange(1, 11)
print("\nArray arr2:")
print(arr2)

result = arr1 + arr2
print("\nResult of element-wise addition:")
print(result)

Array arr1:
[84 67 26 54 66 46 58 10 70 68]

Array arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise addition:
[85 69 29 58 71 52 65 18 79 78]


In [68]:
# 52. Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise.

# code

import numpy as np

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2

print("Array arr1: ", arr1)
print("Array arr2: ", arr2)

print("Result array: ", result)


Array arr1:  [10  9  8  7  6  5  4  3  2  1]
Array arr2:  [ 1  2  3  4  5  6  7  8  9 10]
Result array:  [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [69]:
# 53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2.

# code


import numpy as np

arr1 = np.random.randint(1, 10, size=(5,))
arr2 = np.arange(1, 6)
result = arr1 * arr2[:, np.newaxis]

print("Array arr1: ", arr1)
print("Array arr2: ", arr2)
print("Result array: ", result)

Array arr1:  [6 1 2 4 9]
Array arr2:  [1 2 3 4 5]
Result array:  [[ 6  1  2  4  9]
 [12  2  4  8 18]
 [18  3  6 12 27]
 [24  4  8 16 36]
 [30  5 10 20 45]]


In [70]:
# 54. Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2.

# code


import numpy as np

arr1 = np.arange(2, 13, 2)
arr2 = np.arange(1, 6)

result = arr1 / arr2[:, np.newaxis]

print("Array arr1: ", arr1)
print("Array arr2: ", arr2)
print("Result array: ", result)

Array arr1:  [ 2  4  6  8 10 12]
Array arr2:  [1 2 3 4 5]
Result array:  [[ 2.          4.          6.          8.         10.         12.        ]
 [ 1.          2.          3.          4.          5.          6.        ]
 [ 0.66666667  1.33333333  2.          2.66666667  3.33333333  4.        ]
 [ 0.5         1.          1.5         2.          2.5         3.        ]
 [ 0.4         0.8         1.2         1.6         2.          2.4       ]]


In [71]:
# 55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.

# code


import numpy as np

arr1 = np.array([2, 3, 4, 5, 6])
arr2 = np.array([6, 5, 4, 3, 2])

result = np.power(arr1, arr2)

print("Array arr1: ", arr1)
print("Array arr2: ", arr2)
print("Result array: ", result)

Array arr1:  [2 3 4 5 6]
Array arr2:  [6 5 4 3 2]
Result array:  [ 64 243 256 125  36]


In [72]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
# arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
# code


import numpy as np

def count_substring(arr, substring):

    return np.sum(np.char.find(arr, substring) >= 0)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

result = count_substring(arr, substring)

print("Array: ", arr)
print("Substring: ", substring)
print("Number of occurrences: ", result)

Array:  ['hello' 'world' 'hello' 'numpy' 'hello']
Substring:  hello
Number of occurrences:  3


In [73]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
# arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
# code

import numpy as np

def extract_uppercase_characters(arr):

    uppercase_characters = []
    for string in arr:
        for char in string:
            if char.isupper():
                uppercase_characters.append(char)
    return uppercase_characters

string_array = np.array(["Hello World", "NumPy Arrays", "OpenAI GPT-3", "Data Science"])
print("Original array of strings:")
print(string_array)

uppercase_characters = extract_uppercase_characters(string_array)
print("\nUppercase characters extracted:")
print(uppercase_characters)

Original array of strings:
['Hello World' 'NumPy Arrays' 'OpenAI GPT-3' 'Data Science']

Uppercase characters extracted:
['H', 'W', 'N', 'P', 'A', 'O', 'A', 'I', 'G', 'P', 'T', 'D', 'S']


In [74]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
# code


import numpy as np

def replace_substring(arr, old_substring, new_substring):

    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

result = replace_substring(arr, 'apple', 'orange')

print("Array: ", arr)
print("Replaced array: ", result)

Array:  ['apple' 'banana' 'grape' 'pineapple']
Replaced array:  ['orange' 'banana' 'grape' 'pineorange']


In [75]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.
# arr1 = np.array(['Hello', 'World'])
# arr2 = np.array(['Open', 'AI'])
# code


import numpy as np

def concatenate_strings(arr1, arr2):

    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)

print("Array 1: ", arr1)
print("Array 2: ", arr2)
print("Concatenated array: ", result)

Array 1:  ['Hello' 'World']
Array 2:  ['Open' 'AI']
Concatenated array:  ['HelloOpen' 'WorldAI']


In [76]:
# 60. Write a function that finds the length of the longest string in a NumPy array.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
# code


import numpy as np

def longest_string_length(arr):

    return np.max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

result = longest_string_length(arr)

print("Array: ", arr)
print("Length of longest string: ", result)

Array:  ['apple' 'banana' 'grape' 'pineapple']
Length of longest string:  9


In [77]:

# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

# code


import numpy as np

dataset = np.random.randint(500, 1501, size=50)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print("Dataset: ", dataset)
print("Mean: ", mean)
print("Median: ", median)
print("Variance: ", variance)
print("Standard Deviation: ", std_deviation)

Dataset:  [1058  642 1213  783  954 1058  615 1410  543 1256 1076  890 1079 1457
  663  543  888  509  718  778  576 1008 1301  958  836 1409  803  657
 1232  625  865 1113  881 1010 1312  896  807  541 1084 1289  627  961
 1315  703  647  926 1176  764  810  789]
Mean:  921.08
Median:  889.0
Variance:  67624.95360000001
Standard Deviation:  260.04798326462753


In [78]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

# code


import numpy as np

dataset = np.random.randint(1, 1001, size=100)

q1 = np.percentile(dataset, 20)
q3 = np.percentile(dataset, 80)

print("Dataset: ", dataset)
print("25th percentile: ", q1)
print("75th percentile: ", q3)

Dataset:  [240 849 230 187 380 760 345 407 628  76 516 208 375 319 430  12  35 317
 956  76 649 274 891 834 195 564 490 119 729 281 215 188 100 361 395 789
 574 474 818 981 994 664 909 333 125 405 461 522 225 625 830 114 124 887
 650 334 660 879 331 545 520 420 710  29  85 598 227 819 200 743 168 846
  15 299 367 524 993 574 109 550 735 640 535 388 791 803 477 528 651 996
 523 822 472  86 749 881 162 211 142 549]
25th percentile:  199.0
75th percentile:  765.8000000000001


In [79]:

# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

# code


import numpy as np

array1 = np.array([3, 6, 9, 12, 15])
array2 = np.array([10, 20, 30, 40, 50])

result = np.corrcoef(array1, array2)[0, 1]

print("Array 1: ", array1)
print("Array 2: ", array2)
print("Correlation coefficient: ", result)

Array 1:  [ 3  6  9 12 15]
Array 2:  [10 20 30 40 50]
Correlation coefficient:  1.0


In [80]:

# 64. Create two matrices and perform matrix multiplication using NumPy's dot function.

# code


import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult:")
print(result)

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [81]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

# code

import numpy as np

array = np.random.randint(50, 2001, size=100)

p15 = np.percentile(array, 15)
p60 = np.percentile(array, 60)
p85 = np.percentile(array, 85)

q2 = np.percentile(array, 35)
q4 = np.percentile(array, 70)

print("Array:")
print(array)
print("\nPercentiles:")
print("15th percentile: ", p15)
print("60th percentile: ", p60)
print("85th percentile: ", p85)
print("\nQuartiles:")
print("2nd quartile: ", q2)
print("4th quartile: ", q4)



Array:
[ 440 1135  613 1981 1687 1691  320 1814 1150  365 1072  587  496   91
  313  875  794  914 1362 1336  776 1972  693  147  596  629 1395 1481
 1260 1359 1856  786  346   69 1298 1326  122 1584  435 1100  339  399
 1518  399 1352 1847 1742 1912  880  504  995  420  391 1095  903 1159
 1875  459 1334  939  473 1991  545  697  689 1379  254  884 1372 1857
  494 1660 1349  307 1385 1018  528 1797 1869  485 1393  503 1014  757
  839 1403  848  978 1132  598 1269 1402 1630 1923  235  528 1504 1386
 1532 1129]

Percentiles:
15th percentile:  416.84999999999997
60th percentile:  1199.3999999999999
85th percentile:  1664.0499999999997

Quartiles:
2nd quartile:  695.6
4th quartile:  1365.0


In [83]:
# 66. Create a NumPy array of integers and find the index of a specific element.

# code

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

index = np.where(array == 7)[0][0]

print("Array:")
print(array)
print("\nIndex of 7: ", index)

Array:
[ 1  2  3  4  5  6  7  8  9 10]

Index of 7:  6


In [84]:

# 67. Generate a random NumPy array and sort it in ascending order.

# code


import numpy as np

array = np.random.rand(10)

sorted_array = np.sort(array)

print("Original array:")
print(array)
print("\nSorted array:")
print(sorted_array)

Original array:
[0.67274736 0.34160521 0.2653293  0.58239536 0.94426663 0.24875943
 0.32061993 0.02370621 0.49982291 0.9178291 ]

Sorted array:
[0.02370621 0.24875943 0.2653293  0.32061993 0.34160521 0.49982291
 0.58239536 0.67274736 0.9178291  0.94426663]


In [85]:
# 68. Filter elements >20 in the given NumPy array.
# arr = np.array([12, 25, 6, 42, 8, 30])
# code


import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print("Original array:")
print(arr)
print("\nFiltered array:")
print(filtered_arr)

Original array:
[12 25  6 42  8 30]

Filtered array:
[25 42 30]


In [86]:

# 69. Filter elements which are divisible by 3 from a given NumPy array.
# arr = np.array([1, 5, 8, 12, 15])
# code


import numpy as np

arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]
print("Original array:")
print(arr)
print("\nFiltered array:")
print(filtered_arr)

Original array:
[ 1  5  8 12 15]

Filtered array:
[12 15]


In [87]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])
# code


import numpy as np

arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Original array:")
print(arr)
print("\nFiltered array:")
print(filtered_arr)

Original array:
[10 20 30 40 50]

Filtered array:
[20 30 40]


In [88]:
# 71. For the given NumPy array, check its byte order using the dtype attribute byteorder.
# arr = np.array([1, 2, 3])

# code

import numpy as np
arr = np.array([1, 2, 3])
print("Original array:")
print(arr)

byte_order = arr.dtype.byteorder
print("\nByte order of the array:")
print(byte_order)

if byte_order == '<':
    print("Little-endian")
elif byte_order == '>':
    print("Big-endian")
else:
    print("Native byte order (depends on system endianness)")

Original array:
[1 2 3]

Byte order of the array:
=
Native byte order (depends on system endianness)


In [89]:
# 72. For the given NumPy array, perform byte swapping in place using 'byteswap()`.
# arr = np.array ([1, 2, 3], dtype=np.int32)

# code
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:")
print(arr)

arr.byteswap(True)
print("\nArray after byte swapping:")
print(arr)

Original array:
[1 2 3]

Array after byte swapping:
[16777216 33554432 50331648]


In [90]:

# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
# arr = np.array ([1, 2, 3], dtype=np.int32)
# code

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:")
print(arr)

swapped_array = arr.newbyteorder()
print("\nArray after byte swapping (without modifying the original):")
print(swapped_array)

Original array:
[1 2 3]

Array after byte swapping (without modifying the original):
[16777216 33554432 50331648]


In [91]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
# arr = np.array ([1, 2, 3], dtype=np.int32)

# code
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:")
print(arr)

if arr.dtype.byteorder == '<' or (arr.dtype.byteorder == '=' and np.little_endian):
    swapped_array = arr.newbyteorder()
    print("\nSystem is little-endian. Swapping byte order.")
else:
    swapped_array = arr.copy()
    print("\nSystem is big-endian. No need to swap byte order.")

print("\nArray after conditional byte swapping:")
print(swapped_array)

Original array:
[1 2 3]

System is little-endian. Swapping byte order.

Array after conditional byte swapping:
[16777216 33554432 50331648]


In [92]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using`dtype` attribute 'byteorder`.
# arr = np.array ([1, 2, 3], dtype=np.int32)

# code
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:")
print(arr)

if arr.dtype.byteorder == '<' or (arr.dtype.byteorder == '=' and np.little_endian):
    print("\nSystem is little-endian. Byte swapping is necessary.")
else:
    print("\nSystem is big-endian. Byte swapping is not necessary.")

Original array:
[1 2 3]

System is little-endian. Byte swapping is necessary.


In [93]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

# code


import numpy as np

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()

copy_arr[5] = 50

print("Original array arr1:")
print(arr1)

print("Modified array copy_arr:")
print(copy_arr)

if np.array_equal(arr1, copy_arr):
    print("Modifying copy_arr affects arr1.")
else:
    print("Modifying copy_arr does not affect arr1.")

Original array arr1:
[ 1  2  3  4  5  6  7  8  9 10]
Modified array copy_arr:
[ 1  2  3  4  5 50  7  8  9 10]
Modifying copy_arr does not affect arr1.


In [94]:

# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from  the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

# code
import numpy as np

matrix = np.random.randint(1, 100, size=(3, 3))
print("Original matrix:")
print(matrix)

view_slice = matrix[2:, 2:]
print("\nExtracted slice (view_slice):")
print(view_slice)

view_slice[0, 0] = 999
print("\nModified slice (view_slice):")
print(view_slice)

print("\nMatrix after modifying the slice:")
print(matrix)

Original matrix:
[[53 78 27]
 [46 54 66]
 [88 89  9]]

Extracted slice (view_slice):
[[9]]

Modified slice (view_slice):
[[999]]

Matrix after modifying the slice:
[[ 53  78  27]
 [ 46  54  66]
 [ 88  89 999]]


In [95]:

# 78. Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.

# code
import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)
print("Original array (array_a):")
print(array_a)

view_b = array_a[1:3, :]
print("\nExtracted slice (view_b):")
print(view_b)

view_b += 5
print("\nModified slice (view_b) after broadcasting addition of 5:")
print(view_b)

print("\nOriginal array (array_a) after modifying the slice:")
print(array_a)

Original array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Extracted slice (view_b):
[[4 5 6]
 [7 8 9]]

Modified slice (view_b) after broadcasting addition of 5:
[[ 9 10 11]
 [12 13 14]]

Original array (array_a) after modifying the slice:
[[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [10 11 12]]


In [96]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

# code

import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)
print("Original array (orig_array):")
print(orig_array)

reshaped_view = orig_array.reshape(4, 2)
print("\nReshaped view (reshaped_view):")
print(reshaped_view)

reshaped_view[0, 0] = 999
print("\nModified view (reshaped_view):")
print(reshaped_view)

print("\nOriginal array after modifying the view:")
print(orig_array)

Original array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]

Reshaped view (reshaped_view):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified view (reshaped_view):
[[999   2]
 [  3   4]
 [  5   6]
 [  7   8]]

Original array after modifying the view:
[[999   2   3   4]
 [  5   6   7   8]]


In [97]:

# 80. Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data.

# code
import numpy as np

data = np.random.randint(1, 10, size=(3, 4))
print("Original array (data):")
print(data)

data_copy = data[data > 5].copy()
print("\nCopy of elements greater than 5 (data_copy):")
print(data_copy)

data_copy[0] = 999
print("\nModified copy (data_copy):")
print(data_copy)

print("\nOriginal array (data) after modifying the copy:")
print(data)

Original array (data):
[[3 2 2 4]
 [4 4 4 1]
 [6 7 8 3]]

Copy of elements greater than 5 (data_copy):
[6 7 8]

Modified copy (data_copy):
[999   7   8]

Original array (data) after modifying the copy:
[[3 2 2 4]
 [4 4 4 1]
 [6 7 8 3]]


In [98]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

# code


import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

C_add = A + B
C_sub = A - B

print("Matrix C_add (A + B):")
print(C_add)

print("Matrix C_sub (A - B):")
print(C_sub)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix C_add (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix C_sub (A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [99]:

# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

# code

import numpy as np

import numpy as np

C = np.random.randint(1, 10, size=(3, 2))

D = np.random.randint(1, 10, size=(2, 4))


multiplication_result = np.dot(C, D)

print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Matrix multiplication result:\n", multiplication_result)


Matrix C:
 [[7 4]
 [7 8]
 [9 9]]
Matrix D:
 [[9 7 3 6]
 [9 8 9 4]]
Matrix multiplication result:
 [[ 99  81  57  58]
 [135 113  93  74]
 [162 135 108  90]]


In [100]:

# 83. Create a matrix E and find its transpose.

# code

import numpy as np

E = np.array([[1, 2, 3],
              [4, 5, 6]])

E_transpose = np.transpose(E)

print("Matrix E:\n", E)
print("\nTranspose of matrix E:\n", E_transpose)


Matrix E:
 [[1 2 3]
 [4 5 6]]

Transpose of matrix E:
 [[1 4]
 [2 5]
 [3 6]]


In [101]:
# 84. Generate a square matrix `F` and compute its determinant

# code

import numpy as np

F = np.random.randint(1, 10, size=(3,3))
print("Matrix F:")
print(F)

determinant = np.linalg.det(F)

print("\nDeterminant of matrix F:")
print(determinant)

Matrix F:
[[2 9 3]
 [6 7 1]
 [3 4 1]]

Determinant of matrix F:
-12.0


In [102]:
# 85. Create a square matrix `G` and find its inverse.

# code

import numpy as np

G = np.random.randint(1, 10, size=(4,4))
print("Matrix G:")
print(G)

inverse_G = np.linalg.inv(G)

print("\nInverse of matrix G:")
print(inverse_G)

Matrix G:
[[6 2 6 2]
 [3 3 5 1]
 [8 7 2 5]
 [8 4 6 7]]

Inverse of matrix G:
[[ 0.35810811 -0.31081081  0.10810811 -0.13513514]
 [-0.21621622  0.28828829  0.11711712 -0.06306306]
 [-0.03378378  0.21171171 -0.11711712  0.06306306]
 [-0.25675676  0.00900901 -0.09009009  0.27927928]]
